### ISSUE TITLE
Problems using CYCLeR

### ISSUE THREAD

**Issue by shaoxunyuan** [stiv1n/CYCLeR#1]
Dear Dr. stiv1n,

Thank you for this great software. This software is very helpful.
But when I run it using my own data, I got a problem.
The software needs both circRNA enriched libarary data (mark "enriched" in sample_table) and standard library (mark "control" in sample_table).
If only one of enriched and control, for example, dataset GSE108887, all samples were rRNA-removed, how can I use CYCLeR?

Thank you very much.

**Comment by stiv1n** [comment]
Hi,

1) If you provide a sample table that holds just one replicate of sample type (control or enriched), CYCLeR switches to a "simplified" mode of work. In this case, the normalized values of exons and junctions are directly compared. It does not work as well as if there are replicates, but you will get an output. 

2) I did not notice libraries marked as circRNA-enriched in the dataset -- GSE108887. I am going to assume that you were asking if CYCLeR can be run without a circRNA-enriched library. In that case, the answer is NO.

**Comment by shaoxunyuan** [comment]
Thank you for your reply. Problem solved.
